# Generated by Django 4.1.1 on 2022-09-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='catergory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catergory_name', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('cart_image', models.ImageField(upload_to='categories/photos/')),
            ],
        ),
    ]
