# Generated by Django 4.1.1 on 2022-09-22 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='catergory',
            new_name='category',
        ),
    ]
