# Generated by Django 4.1.1 on 2022-09-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_rename_catergory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catergory_name',
            new_name='category_name',
        ),
    ]
